### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by vitaliemiron** [vordgi/nimpl-classnames-minifier#70]
On build I have this error:

17:44:29 #12 0.774 Error: EBUSY: resource busy or locked, rmdir '/app/.next/cache'
17:44:29 #12 0.774     at rmdirSync (node:fs:1229:10)
17:44:29 #12 0.774     at _rmdirSync (node:internal/fs/rimraf:235:5)
17:44:29 #12 0.774     at rimrafSync (node:internal/fs/rimraf:193:7)
17:44:29 #12 0.774     at node:internal/fs/rimraf:253:9
17:44:29 #12 0.774     at Array.forEach (<anonymous>)
17:44:29 #12 0.774     at _rmdirSync (node:internal/fs/rimraf:250:7)
17:44:29 #12 0.774     at rimrafSync (node:internal/fs/rimraf:193:7)
17:44:29 #12 0.774     at Object.rmSync (node:fs:1278:10)
17:44:29 #12 0.774     at validateDist (/app/node_modules/classnames-minifier/dist/lib/validateDist.js:44:22)
17:44:29 #12 0.774     at new ClassnamesMinifier (/app/node_modules/classnames-minifier/dist/ClassnamesMinifier.js:14:40) {
17:44:29 #12 0.774   errno: -16,
17:44:29 #12 0.774   syscall: 'rmdir',
17:44:29 #12 0.774   code: 'EBUSY',
17:44:29 #12 0.774   path: '/app/.next/cache'
17:44:29 #12 0.774 }

Why does it try to remove .next/cache?

**Comment by vordgi** [comment]
Next.js has a very complex caching system. It caches processed files and doesn't rebuild them during next builds, but takes them from the cache. However, when the package config changes - all these files need to be rebuilt. Without this, there will be critically many artifacts at the intersection of names or unexpected use of previous names.

-------

* Is this process definitely not running in another terminal window?
* Are you sure no files from this folder are open?
* Are there any plugins and utilities that can process these files?
* Can this folder be manually deleted?
* Where exactly and when does this happen - in development mode locally or, for example, in an image on a hosting? How often does the error occur?
* What version of next.js you use?

**Comment by vitaliemiron** [comment]
Hey @vordgi, the problem was that we are using the docker container for deployment.

In that strategy, the .cache directory can't be deleted; 

I fixed it in [my fork](https://github.com/vitaliemiron/classnames-minifier/blob/main/src/lib/validateDist.ts)

**Comment by vitaliemiron** [comment]
sure, thanks @vordgi 

you can test by deploy any next.js app with https://www.flightcontrol.dev
