### ISSUE TITLE
Error on build in 3.1.0

### ISSUE THREAD

**Issue by codefln** [vordgi/nimpl-classnames-minifier#97]
After update to version 3.1.0

I'm getting an error when building:
classnames-minifier: Invalid configuration. Valid keys are: prefix, reservedNames, cacheDir, distDir. See https://github.com/vordgi/classnames-minifier#configuration

```
const withMinifier = classnamesMinifier({
  distDir: 'dist',
  prefix: 'x',
});
```

In version 3.0.0, is ok

**Comment by vordgi** [comment]
Hello. Thank you very much for writing! I apologize for this problem.

Fixed in version 3.1.1.
